backbone:
  type: "sequential"
  layers:
    - ["conv", 3, 16, 3, 1, 1]  # [type, in_c, out_c, kernel, stride, padding]
    - ["relu"]
    - ["maxpool", 2]
    - ["conv", 16, 32, 3, 1, 1]
    - ["relu"]
    - ["maxpool", 2]

head:
  type: "detection"
  args:
    in_channels: 32
    num_classes: 2